### PR TITLE
Update gyp to latest

### PR DESCRIPTION
**Pull request by implausible**
Hey, was working with pangyp and noticed that internally, gyp is 2 years old. Needed `--no-duplicate-basename-check` from the latest build of gyp.

Sidenote: How can I pass this flag into `pangyp configure`

### CODE REVIEW

**Comment by JCMais** [comment]
@rvagg Can you please check this?

It's also needed to compile under Visual Studio 2015.

**Comment by rvagg** [comment]
sorry about the delay, pangyp is low priority for me as it was only ever meant to be temporary, will merge and release with a minor bump now.

**Comment by am11** [comment]
:+1: 
This is also blocking me building node-sass binaries using VS2015.

**Comment by JCMais** [comment]
AFAIK, this was already merged, but @rvagg / @implausible forgot to close this pr.

See commit https://github.com/rvagg/pangyp/commit/6b1641bcd3a89b6f0b47c0913edd69ee4a88d23c

**Comment by am11** [comment]
@JCMais, thanks! Took a closer look, `node_modules/.bin/pangyp rebuild` after `npm install --msvs_version=2015` indeed generates VS2015 `.vcxproj`, but the build script `spawn`s the wrong msbuild version (it blindly [selects the one it finds in PATH](https://github.com/rvagg/pangyp/blob/20db553/lib/build.js#L112)), instead of matching the version of Toolset the project file is requiring.

**Pull request closed without merging**
